CREATE TABLE `USUARIOS` (
  `USUARIO` varchar(45) DEFAULT NULL,
  `CONTRASEÑA` varchar(45) DEFAULT NULL,
  UNIQUE KEY `idx_USUARIOS_USUARIO` (`USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ALUMNOS` (
  `ID` varchar(6) DEFAULT NULL,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `APELLIDO` varchar(45) DEFAULT NULL,
  `DNI` varchar(9) DEFAULT NULL,
  `PROFESOR` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PROFESORES` (
  `ID` varchar(6) NOT NULL,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `APELLIDOS` varchar(45) DEFAULT NULL,
  `DNI` varchar(9) DEFAULT NULL,
  `FALTA` varchar(20) DEFAULT NULL,
  `FBAJA` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;