CREATE TABLE `USUARIOS` (
  `USUARIO` varchar(45) DEFAULT NULL,
  `CONTRASEÑA` varchar(45) DEFAULT NULL,
  UNIQUE KEY `idx_USUARIOS_USUARIO` (`USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USUARIOS` (
  `USUARIO` varchar(45) DEFAULT NULL,
  `CONTRASEÑA` varchar(45) DEFAULT NULL,
  UNIQUE KEY `idx_USUARIOS_USUARIO` (`USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USUARIOS` (
  `USUARIO` varchar(45) DEFAULT NULL,
  `CONTRASEÑA` varchar(45) DEFAULT NULL,
  UNIQUE KEY `idx_USUARIOS_USUARIO` (`USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;