-- STUDENTS definition

CREATE TABLE STUDENTS (
	STUDENT_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FIRST_NAME TEXT NOT NULL,
	"LAST-NAME" TEXT NOT NULL,
	DNI TEXT NOT NULL,
	EMAIL TEXT NOT NULL
);

CREATE UNIQUE INDEX STUDENTS_STUDENT_ID_IDX ON STUDENTS (STUDENT_ID);


-- TEACHERS definition

CREATE TABLE TEACHERS (
	TEACHER_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FIRST_NAME TEXT NOT NULL,
	LAST_NAME TEXT NOT NULL,
	DNI TEXT NOT NULL,
	SUBJECT TEXT NOT NULL,
	EMAIL TEXT NOT NULL
);

CREATE UNIQUE INDEX TEACHERS_TEACHER_ID_IDX ON TEACHERS (TEACHER_ID);


-- USERS definition

CREATE TABLE USERS (
	USERNAME TEXT NOT NULL,
	USER_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	PASSWORD_HASH TEXT NOT NULL
);


-- ASSIGNMENTS definition

CREATE TABLE ASSIGNMENTS (
	ASSIGNMENT_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	TEACHER_ID INTEGER,
	STUNDENT_ID INTEGER,
	DAY_OF_WEEK INTEGER NOT NULL,
	STRAT_TIME TEXT NOT NULL,
	START_DATE TEXT NOT NULL,
	END_DATE TEXT NOT NULL,
	CONSTRAINT ASSIGNMENTS_TEACHERS_FK FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(TEACHER_ID),
	CONSTRAINT ASSIGNMENTS_STUDENTS_FK FOREIGN KEY (STUNDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);