-- Esquema SQLite equivalente al modelo MySQL validado de CSIA.
-- Es idempotente: puede ejecutarse de nuevo sin eliminar tablas ni datos.

CREATE TABLE IF NOT EXISTS ALUMNOS (
    ID VARCHAR(6),
    NOMBRE VARCHAR(45),
    APELLIDO VARCHAR(45),
    DNI VARCHAR(9),
    PROFESOR VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS PROFESORES (
    ID VARCHAR(6) NOT NULL,
    NOMBRE VARCHAR(45),
    APELLIDOS VARCHAR(45),
    DNI VARCHAR(9),
    FALTA VARCHAR(20),
    FBAJA VARCHAR(20),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USUARIOS (
    USUARIO VARCHAR(45),
    CONTRASEÑA VARCHAR(45)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_USUARIOS_USUARIO
    ON USUARIOS (USUARIO);
